using System.Text.Json.Serialization;

namespace Cominomi.Shared.Models;

/// <summary>
/// Deserialization model for ~/.claude/stats-cache.json
/// (generated by Claude CLI's external stats indexer).
/// </summary>
public class StatsCache
{
    [JsonPropertyName("version")]
    public int Version { get; set; }

    [JsonPropertyName("lastComputedDate")]
    public string LastComputedDate { get; set; } = "";

    [JsonPropertyName("dailyActivity")]
    public List<StatsCacheDailyActivity> DailyActivity { get; set; } = [];

    [JsonPropertyName("dailyModelTokens")]
    public List<StatsCacheDailyModelTokens> DailyModelTokens { get; set; } = [];

    [JsonPropertyName("modelUsage")]
    public Dictionary<string, StatsCacheModelUsage> ModelUsage { get; set; } = new();

    [JsonPropertyName("hourCounts")]
    public Dictionary<string, int> HourCounts { get; set; } = new();

    [JsonPropertyName("totalSessions")]
    public int TotalSessions { get; set; }

    [JsonPropertyName("totalMessages")]
    public int TotalMessages { get; set; }

    [JsonPropertyName("longestSession")]
    public StatsCacheLongestSession? LongestSession { get; set; }

    [JsonPropertyName("firstSessionDate")]
    public DateTime? FirstSessionDate { get; set; }
}

public class StatsCacheDailyActivity
{
    [JsonPropertyName("date")]
    public string Date { get; set; } = "";

    [JsonPropertyName("messageCount")]
    public int MessageCount { get; set; }

    [JsonPropertyName("sessionCount")]
    public int SessionCount { get; set; }

    [JsonPropertyName("toolCallCount")]
    public int ToolCallCount { get; set; }
}

public class StatsCacheDailyModelTokens
{
    [JsonPropertyName("date")]
    public string Date { get; set; } = "";

    [JsonPropertyName("tokensByModel")]
    public Dictionary<string, long> TokensByModel { get; set; } = new();
}

public class StatsCacheModelUsage
{
    [JsonPropertyName("inputTokens")]
    public long InputTokens { get; set; }

    [JsonPropertyName("outputTokens")]
    public long OutputTokens { get; set; }

    [JsonPropertyName("cacheReadInputTokens")]
    public long CacheReadInputTokens { get; set; }

    [JsonPropertyName("cacheCreationInputTokens")]
    public long CacheCreationInputTokens { get; set; }
}

public class StatsCacheLongestSession
{
    [JsonPropertyName("sessionId")]
    public string SessionId { get; set; } = "";

    [JsonPropertyName("duration")]
    public long Duration { get; set; }

    [JsonPropertyName("messageCount")]
    public int MessageCount { get; set; }

    [JsonPropertyName("timestamp")]
    public DateTime Timestamp { get; set; }
}
